### ISSUE TITLE
Error: Cannot find module '.../vendor/actions-yaml-dist/index.js'

### ISSUE THREAD

**Issue by friederbluemle** [mislav/gh-lint-workflow#1]
```
$ gh lint-workflow .github/workflows/ci.yml
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '<current-directory>/vendor/actions-yaml-dist/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v17.0.1
```

It looks like it is trying to look for the `vendor/` folder in the current directory..

**Comment by mislav** [comment]
Thanks for reporting! https://github.com/mislav/gh-lint-workflow/commit/271d0c8529790f02bf728779521b8b552efa702e
